---
openapi: 3.0.1
info:
  title: CryptIn API
  version: v1
paths:
  "/api/v1/accounts":
    post:
      summary: create account
      tags:
      - Accounts
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
              required:
              - user_id
  "/api/v1/accounts/{id}":
    get:
      summary: show account
      tags:
      - Accounts
      parameters:
      - name: id
        in: path
        description: id
        default: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/coin_wallets":
    post:
      summary: create coin_wallet
      tags:
      - CoinWallet
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet_id:
                  type: integer
                coin_id:
                  type: integer
              required:
              - wallet_id
              - coin_id
    get:
      summary: list coin_wallets
      tags:
      - CoinWallet
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    balance:
                      type: string
                    coin_id:
                      type: integer
                    wallet_id:
                      type: integer
                    created_at:
                      type: datetime
                    updated_at:
                      type: datetime
  "/api/v1/coin_wallets/{id}":
    get:
      summary: show coin_wallet
      tags:
      - CoinWallet
      parameters:
      - name: id
        in: path
        description: id
        default: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/coins":
    get:
      summary: list coins
      tags:
      - Coins
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    acronym:
                      type: string
                    created_at:
                      type: datetime
                    updated_at:
                      type: datetime
    post:
      summary: create coin
      tags:
      - Coins
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                acronym:
                  type: string
              required:
              - name
              - acronym
  "/api/v1/operations":
    post:
      summary: create operation
      tags:
      - Operation
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                kind:
                  type: integer
                wallet_origin_id:
                  type: integer
                wallet_destination_id:
                  type: integer
                coin_id:
                  type: integer
              required:
              - wallet_origin_id
              - wallet_destination_id
              - coin_id
              - kind
    get:
      summary: list operations
      tags:
      - Operation
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    kind:
                      type: integer
                    amount:
                      type: string
                    coin_id:
                      type: integer
                    wallet_origin_id:
                      type: integer
                    wallet_destination_id:
                      type: integer
                    created_at:
                      type: datetime
                    updated_at:
                      type: datetime
  "/api/v1/operations/{id}":
    get:
      summary: show operation
      tags:
      - Operation
      parameters:
      - name: id
        in: path
        description: id
        default: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/transitions":
    post:
      summary: create transition
      tags:
      - Transitions
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: integer
                amount:
                  type: decimal
              required:
              - account_id
              - amount
    get:
      summary: list transitions
      tags:
      - Transitions
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    amount:
                      type: string
                    account_id:
                      type: integer
                    created_at:
                      type: datetime
                    updated_at:
                      type: datetime
  "/api/v1/transitions/{id}":
    get:
      summary: show transition
      tags:
      - Transitions
      parameters:
      - name: id
        in: path
        description: id
        default: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/auth":
    post:
      summary: create user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  default: Felipe Maciel
                email:
                  type: string
                  default: felipemrvieira@gmail.com
                password:
                  type: string
                  default: 123123
              required:
              - name
              - email
              - password
  "/api/v1/auth/sign_in":
    post:
      summary: login user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  default: felipemrvieira@gmail.com
                password:
                  type: string
                  default: 123123
              required:
              - email
              - password
  "/api/v1/wallets":
    post:
      summary: create wallet
      tags:
      - Wallets
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: integer
              required:
              - account_id
  "/api/v1/wallets/{id}":
    get:
      summary: show wallet
      tags:
      - Wallets
      parameters:
      - name: id
        in: path
        description: id
        default: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
- url: http://remote
